// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBN1u0KFwT7fX1QsZaJhqSFlngI3pDgvsQ',
    appId: '1:570596588869:web:9f00b447df9dd6f23e122c',
    messagingSenderId: '570596588869',
    projectId: 'fixio-flutter-project',
    authDomain: 'fixio-flutter-project.firebaseapp.com',
    storageBucket: 'fixio-flutter-project.firebasestorage.app',
    measurementId: 'G-JDKNM54E8C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcGI0732_P5PWZv7xAY8XqPCHw9MsAUXc',
    appId: '1:570596588869:android:0996bd85865954d73e122c',
    messagingSenderId: '570596588869',
    projectId: 'fixio-flutter-project',
    storageBucket: 'fixio-flutter-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWorek1EleR8uleeMbbodM39D3uxfTcYs',
    appId: '1:570596588869:ios:416110bc2cb6b6fb3e122c',
    messagingSenderId: '570596588869',
    projectId: 'fixio-flutter-project',
    storageBucket: 'fixio-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.missMenageAppl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWorek1EleR8uleeMbbodM39D3uxfTcYs',
    appId: '1:570596588869:ios:416110bc2cb6b6fb3e122c',
    messagingSenderId: '570596588869',
    projectId: 'fixio-flutter-project',
    storageBucket: 'fixio-flutter-project.firebasestorage.app',
    iosBundleId: 'com.example.missMenageAppl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBN1u0KFwT7fX1QsZaJhqSFlngI3pDgvsQ',
    appId: '1:570596588869:web:a9ec8012bbfecba93e122c',
    messagingSenderId: '570596588869',
    projectId: 'fixio-flutter-project',
    authDomain: 'fixio-flutter-project.firebaseapp.com',
    storageBucket: 'fixio-flutter-project.firebasestorage.app',
    measurementId: 'G-B2YZ46EDKK',
  );
}
